# Site settings
title: Summernote - Super Simple WYSIWYG editor
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Super Simple WYSIWYG Editor on Bootstrap
  Summernote is a JavaScript library that helps you create WYSIWYG editors online.
author: https://github.com/hackerwins
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://summernote.org" # the base hostname & protocol for your site
github_username: summernote
version: v0.7.0

# Build settings
markdown: kramdown
