# Site settings
title: Summernote - Super Simple WYSIWYG editor
email: summernoteis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Super Simple WYSIWYG Editor on Bootstrap
  Summernote is a JavaScript library that helps you create WYSIWYG editors online.
author: https://github.com/summernote
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://summernote.org" # the base hostname & protocol for your site
github_username: summernote

# Summernote settings
version: 0.8.6
repository: "https://github.com/summernote/summernote"
jquery_js: "http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"
bootstrap_css: "http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css"
bootstrap_js: "http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"
summernote_js: "http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.6/summernote.js"
summernote_css: "http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.6/summernote.css"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
